version: '2'
services:
  puppeteer:
    image: 0.1.64c552ff6df9c2e27f9613df1c4cf4c58c97e444
    user: $USER
    cap_add:
      - SYS_ADMIN
    shm_size: 512M
    cpuset: 0-1
    volumes:
      - .:/app
    tty: true
    stdin_open: true
